server:
  port: 9191
spring:
  h2:
    console:
      enabled: true
  application:
    name: ORDER-SERVICE
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9190/eureka/
  instance:
    hostname: localhost
